name: Daily MarketPulse Pipeline

on:
  workflow_dispatch: {}
  schedule:
    # Run every day at 13:00 UTC (adjust if you want)
    - cron: "0 13 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      # Passed from GitHub → Settings → Secrets and variables → Actions → New repository secret
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      SENTIMENT_MODEL_REPO: ${{ secrets.SENTIMENT_MODEL_REPO }}
      # Streamlit uses this file in the app, but our runner reads env directly.
      # (No need to mount secrets.toml here.)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily pipeline
        run: |
          python daily_runner.py
